### ISSUE TITLE
Throws exception if --console not specified

### ISSUE THREAD

**Issue by isaacrlevin** [spboyer/dotnet-doc#2]
I followed the instructions and tried to search and get this error

````
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 1447ms.
 PS> dotnet install tool -g dotnet-doc

The installation succeeded. If there are no further instructions, you can type the following command in shell directly to invoke: docs
 PS> docs mvc

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ConsoleApplication.Program.OpenResult(String url) in /Users/shayneboyer/github/spboyer/dotnet-doc/Program.cs:line 102
   at ConsoleApplication.Program.OnExecute(CommandLineApplication app) in /Users/shayneboyer/github/spboyer/dotnet-doc/Program.cs:line 78
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 86
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<OnExecute>d__1.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 31
   at ConsoleApplication.Program.Main(String[] args) in /Users/shayneboyer/github/spboyer/dotnet-doc/Program.cs:line 38

````

Looks like some search work, for instance this works

> docs '.NET Docker' --console --number 3  

but this fails

> docs 'mvc 5'

So it looks like not adding the console flag causes an exception

**Comment by spboyer** [comment]
This is a Windows specific issue.

```csharp
// macOS
Process.Start("open", url);

// Linux
Process.Start("xdg-open", url);

// Windows - should be....
Process.Start(url)

// OR 
Process.Start("start", url);
```

This works in Full Framework for Windows, not in .NET Core.  Fails specifically with the error

```bash
System.ComponentModel.Win32Exception: The system cannot find the file specified
```
There are a few reasons this fails:

* urls are not considered documents or files [see docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo?view=netcore-2.0)
* If IE is not set as the default browser, at least for Full Framework, it fails.

**Comment by spboyer** [comment]
Thanks to this one article here - we have a solution to this - http://www.seirer.net/blog/2014/6/10/solved-how-to-open-a-url-in-the-default-browser-in-csharp.

**Comment by spboyer** [comment]
Fixed in https://github.com/spboyer/dotnet-doc/commit/7ab9a153c3ec5f9c6d9021eb7f5e8bba70c3e743

[Install version 1.0.2](https://www.nuget.org/packages/dotnet-doc/1.0.2)
